Custom s3
mluggy/teslabox pull request #29
Opened 2023-08-24 07:23 UTC by jheredianet

This is a change for setup another S3 compatible cloud service as discussed here https://github.com/mluggy/teslabox/issues/26

With this, you'll have the option to use to use a bucket from another compatible S3 Cloud Service or your own bucket (ex. Minio)

2023-08-29 21:32 UTC, mluggy requested changes
looks great, just a couple of small changes?

2023-08-29 21:32 UTC, mluggy commented on src/aws/s3.js
> +  if (typeof settings.endpoint === null || settings.endpoint.length === 0){
```if (!settings.endpoint) {```
usually enough

2023-08-29 21:32 UTC, mluggy commented on README.md
> +  - If you are planning to use a bucket from another compatible S3 Cloud Service or your own bucket (ex. Minio), uncomment the S3_ENDPOINT environment variable and fill it up with the corresponding e
can you give an example for an endpoint URL?

2023-08-29 22:27 UTC, jheredianet commented on README.md
> +  - If you are planning to use a bucket from another compatible S3 Cloud Service or your own bucket (ex. Minio), uncomment the S3_ENDPOINT environment variable and fill it up with the corresponding e
Yes sure! (Keys are just an example sample)

It would be something like this (assuming that I'm using my own S3 Buket):

Environment="AWS_ACCESS_KEY_ID=7RbAnOAScdJQYxxA1aX4LJ"
Environment="AWS_SECRET_ACCESS_KEY=LrkEh1u0S3YkxxxxVYmnNg5cqLYnU7iiDSQieWoPZima"
Environment="AWS_DEFAULT_REGION=nome"
Environment="AWS_S3_BUCKET=sentry"
Environment="S3_ENDPOINT='https://minio.mydomain.com"

Or something like this (asuming I'm using Wasabi cloud):

Environment="AWS_ACCESS_KEY_ID=OV5M2M06FONQNOIV4IxGC"
Environment="AWS_SECRET_ACCESS_KEY=KkJaIR9NegQhezXw0zdM40c7WikCpirgBOIOqLWe"
Environment="AWS_DEFAULT_REGION=nome"
Environment="AWS_S3_BUCKET=sentry"
Environment="S3_ENDPOINT='https://s3.eu-west-2.wasabisys.com"

2023-08-29 22:30 UTC, jheredianet commented on src/aws/s3.js
> +  if (typeof settings.endpoint === null || settings.endpoint.length === 0){
Yes, sure! the last commit is as you suggest.

2023-08-31 15:45 UTC, mluggy approved these changes

2023-08-31 15:47 UTC, mluggy approved these changes

2023-08-31 15:47 UTC, merged